CATEGORY CHANNEL REMOVER LICENSE
---------------------------------

THIS SOFTWARE IS PROVIDED "AS IS," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

THIS SCRIPT IS INTENDED FOR EDUCATIONAL AND ADMINISTRATIVE PURPOSES ONLY. YOU MAY USE IT TO REMOVE CATEGORY CHANNELS THAT YOU OWN OR HAVE ADMINISTRATIVE RIGHTS TO. ANY USE OF THIS SCRIPT FOR MALICIOUS PURPOSES, INCLUDING UNAUTHORIZED REMOVAL OF CHANNELS FROM SERVERS OR PLATFORMS WHERE YOU DO NOT HAVE PERMISSION, IS STRICTLY PROHIBITED.

BY USING THIS SOFTWARE, YOU AGREE THAT YOU TAKE FULL RESPONSIBILITY FOR YOUR ACTIONS AND ANY CONSEQUENCES THAT ARISE FROM ITS USE. THE AUTHOR WILL NOT BE HELD RESPONSIBLE FOR ANY DAMAGE OR LOSS CAUSED BY IMPROPER USE OF THIS SCRIPT.

YOU ARE FREE TO MODIFY OR DISTRIBUTE THIS SOFTWARE, PROVIDED THAT THIS LICENSE IS INCLUDED IN ALL COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE.

MADE BY TRAP
